# Generated by Django 3.0.5 on 2020-09-17 14:56

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=8)),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_api_key', models.CharField(max_length=40)),
                ('write_api_key', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
