# Generated by Django 3.0.5 on 2020-09-18 17:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=16),
        ),
        migrations.AlterField(
            model_name='channel',
            name='values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=16),
        ),
    ]
