# Generated by Django 3.1.1 on 2020-09-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='isGreater',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='threshold_value',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Threshold',
        ),
    ]
