# Generated by Django 3.1.1 on 2020-09-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0004_auto_20200920_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='isGreater',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='threshold_value',
        ),
    ]
